name: "Powerwall3 to MQTT"
description: "A bridge between a Tesla Powerwall3 and MQTT"
version: "0.1.0"
slug: "powerwall3mqtt"
url: "https://github.com/slyglif/haos-addons/powerwall3mqtt"
init: false
stage: experimental
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
services:
  - mqtt:need
options:
  tedapi_report_vitals: false
  tedapi_poll_interval: 30
  mqtt_base_topic: "homeassistant"
  mqtt_ssl: false
schema:
  log_level: "list(DEBUG|INFO|WARNING|ERROR|CRITICAL)?"
  tedapi_password: str
  tedapi_report_vitals: bool
  tedapi_poll_interval: "int(5,300)"
  mqtt_base_topic: str
  mqtt_server: "str?"
  mqtt_port: "port?"
  mqtt_ssl: bool
  mqtt_ca: "str?"
  mqtt_key: "str?"
  mqtt_cert: "str?"
  mqtt_verify_tls: "bool?"
  mqtt_user: "str?"
  mqtt_password: "str?"
